<?php
$this->FlashMessengerHelper();
?>
<div>
    <div class="row profile-account">
        <div class="col-md-12">
            <div class="tab-content">
                <div>
                    <?=$this->DoctrinGuiNavHelper();?>
                    <p>
                        The client in this section is used:</p>
                        <ul>
                            <li>To log users via SSO into your game (grant: implicit)</li>
                            <li>For server side access (grant: urn:ietf:params:oauth:grant-type:jwt-bearer)</li>
                        </ul>


                    <p>
                        We offer two types of scopes: </p>
                        <ul>
                            <li>Basic: Allows the client to access basic user information</li>
                            <li>Transfer: Allows the client to initiate a transfer</li>
                        </ul>
                    <p>
                        While it is possible to have a single client with all access levels, we would suggest you create a client
                        to handle SSO access (<b>grant type:</b> implicit  / <b>scope:</b> basic) and a server side client to manage payments
                        (<b>grant type: </b>params:oauth:grant-type:jwt-bearer / <b>scope:</b> basic, transfer).
                    </p>
                    <p>
                        <b>Naming convention:</b> name your clients appropriately to avoid confusion: i.e. game_name_sso_client, game_name_sso_client_test, game_name_server_client, game_name_server_client_test
                    </p>
                    <p>
                        <a class="btn btn-xs blue" href="<?=$this->url('developer/client-manage');?>">
                            <i class="fa fa-cloud"></i> New client</a>
                    </p>
                    <div class="col-md-12">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Details</th>
                                <th>Public key</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                foreach ($client_array AS $client ) {
                            ?>
                            <tr>
                                <td>
                                    <b>Client ID:</b> <?=$client['array_copy']['clientId'];?><br/>
                                    <b>Subject:</b> <?= (isset($client['public_key']['subject'])) ? $client['public_key']['subject'] : 'Add public key to set';?><br/>
                                    <b>Return uri:</b> <?=($client['array_copy']['redirectUri'] == '') ? 'This must be set for security purposes' : $client['array_copy']['redirectUri'];?><br/>
                                    <b>Grant:</b> <?=implode(', ',$client['array_copy']['grantType']);?><br/>
                                    <b>Scope:</b> <?=var_dump($client['scope']);?><br/>
                                    <p>
                                        <a class="btn default btn-xs green" href="<?=$this->url('developer/client-manage', ['client_id' => $client['array_copy']['id']]);?>">
                                            <i class="fa fa-cloud"></i> Edit Client</a>

                                            <a class="btn default btn-xs blue" href="<?=$this->url('developer/manage-key', ['client_id' => $client['array_copy']['id'] , 'jwt_id' => 0]);?>">
                                                <i class="fa fa-key"></i> Add Public Key</a>

                                        <a class="btn btn-primary btn-xs red" href="<?=$this->url('developer/delete-client', ['client_id' => $client['array_copy']['id']]);?>">
                                            <i class="fa fa-key"></i> Delete Client</a><br/><br/>

                                        <?php if (in_array('implicit',$client['array_copy']['grantType'])) { ?>
                                        <a class="btn default btn-xs grey" target="_blank" href="<?=$this->app_url;?>/oauth/authorize?client_id=<?=$client['array_copy']['clientId'];?>&response_type=token&state=your_random_token&redirect_uri=<?=$client['array_copy']['redirectUri'];?>">
                                            <i class="fa fa-cloud-download"></i> Test SSO Login</a>
                                        <?php } ?>

                                        <?php
                                        if ( in_array('urn:ietf:params:oauth:grant-type:jwt-bearer',$client['array_copy']['grantType']) AND !empty($client['public_key']) ) { ?>
                                            <a class="btn default btn-xs grey" href="<?=$this->url('developer/test-jwt' , [ 'jwt_id' => $client['public_key']['id'] , 'client_id' => $client['array_copy']['id'] ]);?>">
                                                <i class="fa fa-cloud-upload"></i> Test JWT Authentication</a>
                                        <?php }  ?>

                                    </p>
                                </td>
                                <td>
                                    <?php
                                        if ( is_array($client['public_key']) AND ! empty($client['public_key'])  )
                                        {
                                    ?>
                                    <textarea cols="60" rows="3" disabled><?=$client['public_key']['key'];?></textarea><br/>
                                            <a class="btn btn-primary btn-xs green" href="<?=$this->url('developer/manage-key', ['jwt_id' => $client['public_key']['id']]);?>">
                                                <i class="fa fa-key"></i> Edit Public Key</a>
                                            <a class="btn btn-primary btn-xs red" href="<?=$this->url('developer/delete-jwt-key', ['jwt_id' => $client['public_key']['id']]);?>">
                                                <i class="fa fa-key"></i> Delete Key</a><br/><br/>

                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>

    </div>
</div>