<?php
$this->layout('doctrine-gui/layout');
?>
<?php
$this->layout('doctrine-gui/layout');
?>
<?php
$this->FlashMessengerHelper();
?>

<div>
    <div class="row profile-account">
        <div class="col-md-12">
            <div class="tab-content">
                <div>
                    <p>
                        Use the OAuth2 Doctrine Gui to create clients for your API!
                    </p>
                </div>
            </div>
        </div>

    </div>
</div>