<?php
$this->FlashMessengerHelper();
?>
<div>
    <div class="row profile-account">
        <div class="col-md-12">
            <div class="tab-content">
                <div>
                    <?=$this->DoctrinGuiNavHelper();?>
                    <p>
                        A publisher is a name you use to describe an entity that creates games for GamblingTec.com. It may be
                        a company name or your name or anything you choose. Please contact us to add a publisher to your account
                        and the name of the game(s) you will be working on. Each game will be listed in the games section and will
                        be associated to a unique code that you will require.
                    </p>
                    <p>
                        Use the clients section to create your Oauth2 client used to consume the GamblingTec.com API.
                    </p>
                    <div class="col-md-12">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Publisher Account</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                                foreach ($publisher_array AS $publisher_id => $game_name) {
                            ?>
                            <tr>
                                <td><?=$game_name;?></td>
                                <td>
                                    <a class="btn default btn-xs green" href="<?=$this->url('developer/games' , ['publisher_id' => $publisher_id]);?>">
                                        <i class="fa fa-gamepad"></i> View Games</a>
                                </td>
                            </tr>
                            <?php } ?>
                            </tbody>
                        </table>
                    </div>


                </div>
            </div>
        </div>

    </div>
</div>